name: TypeScript CI
on:
  push:
    branches: [master]
  pull_request:
    paths:
      - "ts/**"

jobs:
  lint-and-check-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm using local-setup script
        run: |
          source deno/local-setup.sh
          # Make sure .local/bin is added to PATH for subsequent steps
          echo "$PWD/.local/bin" >> $GITHUB_PATH
          deno --version

      - name: Install deps
        working-directory: ./ts
        run: pnpm install

      - name: Check
        working-directory: ./ts
        run: pnpm run -r check
